config/routes.rb
Rails.application.routes.draw do
  resources :learners
  get 'logic/think'

  get 'logic/good'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/learner.rb
class Learner < ApplicationRecord
end

app/models/nice.rb
class Nice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/learners_controller.rb
class LearnersController < ApplicationController
  before_action :set_learner, only: [:show, :edit, :update, :destroy]

  # GET /learners
  # GET /learners.json
  def index
    @learners = Learner.all
  end

  # GET /learners/1
  # GET /learners/1.json
  def show
  end

  # GET /learners/new
  def new
    @learner = Learner.new
  end

  # GET /learners/1/edit
  def edit
  end

  # POST /learners
  # POST /learners.json
  def create
    @learner = Learner.new(learner_params)

    respond_to do |format|
      if @learner.save
        format.html { redirect_to @learner, notice: 'Learner was successfully created.' }
        format.json { render :show, status: :created, location: @learner }
      else
        format.html { render :new }
        format.json { render json: @learner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learners/1
  # PATCH/PUT /learners/1.json
  def update
    respond_to do |format|
      if @learner.update(learner_params)
        format.html { redirect_to @learner, notice: 'Learner was successfully updated.' }
        format.json { render :show, status: :ok, location: @learner }
      else
        format.html { render :edit }
        format.json { render json: @learner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learners/1
  # DELETE /learners/1.json
  def destroy
    @learner.destroy
    respond_to do |format|
      format.html { redirect_to learners_url, notice: 'Learner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learner
      @learner = Learner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def learner_params
      params.require(:learner).permit(:name, :technology, :duration, :fee)
    end
end

app/controllers/logic_controller.rb
class LogicController < ApplicationController
  def think
  end

  def good
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/learners_helper.rb
module LearnersHelper
end

app/helpers/logic_helper.rb
module LogicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HardTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/learners/_form.html.erb
<%= form_with(model: learner, local: true) do |form| %>
  <% if learner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(learner.errors.count, "error") %> prohibited this learner from being saved:</h2>

      <ul>
      <% learner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :learner_name %>
  </div>

  <div class="field">
    <%= form.label :technology %>
    <%= form.text_field :technology, id: :learner_technology %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, id: :learner_duration %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.number_field :fee, id: :learner_fee %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/learners/edit.html.erb
<h1>Editing Learner</h1>

<%= render 'form', learner: @learner %>

<%= link_to 'Show', @learner %> |
<%= link_to 'Back', learners_path %>

app/views/learners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Learners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Technology</th>
      <th>Duration</th>
      <th>Fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @learners.each do |learner| %>
      <tr>
        <td><%= learner.name %></td>
        <td><%= learner.technology %></td>
        <td><%= learner.duration %></td>
        <td><%= learner.fee %></td>
        <td><%= link_to 'Show', learner %></td>
        <td><%= link_to 'Edit', edit_learner_path(learner) %></td>
        <td><%= link_to 'Destroy', learner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Learner', new_learner_path %>

app/views/learners/new.html.erb
<h1>New Learner</h1>

<%= render 'form', learner: @learner %>

<%= link_to 'Back', learners_path %>

app/views/learners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @learner.name %>
</p>

<p>
  <strong>Technology:</strong>
  <%= @learner.technology %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @learner.duration %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @learner.fee %>
</p>

<%= link_to 'Edit', edit_learner_path(@learner) %> |
<%= link_to 'Back', learners_path %>

app/views/logic/good.html.erb
<h1>Logic#good</h1>
<p>Find me in app/views/logic/good.html.erb</p>

app/views/logic/think.html.erb
<h1>Logic#think</h1>
<p>Find me in app/views/logic/think.html.erb</p>